#!/bin/bash

# Check if running with root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Modify /etc/hosts file
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' /etc/hosts
sed -i 's/157.240.11.35\sfacebook.com/8.8.8.8 facebook.com/g' /etc/hosts

echo "Hosts file updated. Changes will take effect after a reboot."
